site_name: Tristan Programming Language

# TODO: Fix the site url such that the blogging plugin shuts up
site_url: http:///

# TODO: We must host fonts locally
# https://t.pxeger.com/mkdocs-material/setup/changing-the-fonts/

repo_url: http://deavmi.assigned.network/git/tlang/tlang
repo_name: tlang/tlang

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - search.highlight
  palette:
    primary: indigo

plugins:
    # - blog
    - search
    #- mermaid2

    
    - section-index
    #- git-committers-2
    - git-revision-date

    - tooltips
    #- mknotebooks

    - blogging:
          dirs:
            - journal
          features:
            tags: {}

    - print-site

#TODO: See if we can get git commit authors automatically on each page
#TODO: See if we can ehnace material docs theme

extra_css:
  - css/hint.min.css

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde


  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true 

  - admonition
  - pymdownx.details

  - pymdownx.tasklist:
      custom_checkbox: true

  - attr_list

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


